version: '3'
services:
  ai-ml-e:
    build: .
    image: machine-learning-project-walkthrough
    volumes:
      - ./:/machine-learning-project-walkthrough
    ports:
      - "8888:8888"
    working_dir: /machine-learning-project-walkthrough
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
